---
- name: Enable without reboot
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  with_items: "{{ webspheremq.sysctl_settings }}"
  become: yes

- name: Set user limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
    use_max: yes
  with_items: "{{ webspheremq_internal.user_limits }}"
  become: yes

- name: Ensure Install package is available
  stat:
    path: "{{ webspheremq_internal.install_archive_path }}"
  register: package

- name: Fail when package unavailable
  fail: "msg='Install archive not found path: {{ webspheremq_internal.install_archive_path }}'"
  when: package.stat.exists == False

- name: Unarchive install archive
  unarchive: src="{{ webspheremq_internal.install_archive_path }}" dest="{{ webspheremq.unarchive_dir }}" copy=no
  become: yes

- name: Accept License
  shell: chdir="{{ webspheremq.unarchive_dir }}" ./mqlicense.sh -accept
  become: yes

- name: Find rpms
  shell: chdir="{{ webspheremq.unarchive_dir }}" ls {{ item }}
  with_items: "{{ webspheremq.rpm_fileglobs }}"
  register: rpms
  become: yes

- name: Install rpm packages
  yum:
    name: "{{ webspheremq.unarchive_dir }}/{{ item.stdout }}"
    state: present
  with_items: "{{ rpms.results }}"
  become: yes

- name: setmqinst path
  shell: chdir=/opt/mqm/bin ./setmqinst -i -p /opt/mqm

- name: Update mqm user .profile
  template:
    owner: "{{ webspheremq.user }}"
    group: "{{ webspheremq.group }}"
    src: .profile.j2
    dest: "/home/mqm/.profile"
    mode: "0644"

#- name: Queue Manager Creation
#  shell: crtmqm -c "policy Center Dev" -ld {{ webspheremq_log_directory }} -md {{ webspheremq_data_directory }} -lc -lf  16384 -lp 150 -ls 50 -u {{ webspheremq.QUEUE_NAME }}.DEAD.QUEUE {{ webspheremq.QUEUE_NAME }}
#  become_user: "{{ webspheremq.user }}"
#  become: yes

#- name: Listener Creation
#  shell:
#   ctrmqm -c "policy Center Dev" -ld {{ webspheremq_log_directory }} -md {{ webspheremq_data_directory }} -lc -lf  16384 -lp 150 -ls 50 -u GWPCDEV.DEAD.QUEUE GWPCDEV